app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

brand:
    type:     rest
    resource: AppBundle\Controller\BrandController

order:
    type:     rest
    resource: AppBundle\Controller\OrderController

products:
    type:     rest
    resource: AppBundle\Controller\ProductController