AppBundle\Entity\Brand:
    attributes:
        id:
            groups: ['brand', 'product']
        name:
            groups: ['brand', 'product']
        products:
            groups: ['brand']

AppBundle\Entity\Product:
    attributes:
        id:
            groups: ['brand', 'product']
        name:
            groups: ['brand', 'product']
        brand:
            groups: ['product']
        price:
            groups: ['brand', 'product']

AppBundle\Entity\Order:
    attributes:
        id:
            groups: ['order', 'product']
        mobiles:
            groups: ['order', 'product']
        customer_email:
            groups: ['order', 'product']
        amount:
            groups: ['order', 'product']
        created:
            groups: ['order', 'product']